### ISSUE TITLE
geolocator, Cordova 4.x and up on Android

### ISSUE THREAD

**Issue by MuTLY** [onury/geolocator#14]
Hello,

Recently, I updated Cordova to the latest version (5.0.0) and along with it my Cordova project for an app using AngularJS and out of the blue the geolocator stopped working.

I'm aware of some new access rules for Cordova 4.x+ and I applied those to the app:

http://cordova.apache.org/docs/en/5.0.0/guide_appdev_whitelist_index.md.html#Whitelist%20Guide
https://github.com/apache/cordova-plugin-whitelist

The app is - apparently - working OK on the browser but when I build it with Cordova it doesn't work anymore (the geolocator plugin, I mean).

Peeking on the console of a device running the app, I noticed a 404 error (the geolocator plugin is sitting on the javascript.plugins.min.js file on my app among other plugins):

    Failed to load resource: the server responded with a status of 404 (Not Found): https://www.google.com/jsapi?callback=geolocator.__glcb
    
    javascript.plugins.min.js:15
    GET https://www.google.com/jsapi?callback=geolocator.__glcb
    m @ javascript.plugins.min.js:15
    p @ javascript.plugins.min.js:16
    locate @ javascript.plugins.min.js:22
    (anonymous function) @ pesm-service.js:162
    (anonymous function) @ angular.min.js:139
    e @ angular.min.js:41
    (anonymous function) @ angular.min.js:45
    pesm-service.js:129 onGeoError
    pesm-service.js:130 Error: Could not load source at https://www.google.com/jsapi {stack: "Error: Could not load source at https://www.google…id_asset/www/js/javascript.plugins.min.js:15:429)",message: "Could not load source at https://www.google.com/jsapi"}
    message: "Could not load source at https://www.google.com/jsapi"
    stack: "Error: Could not load source at https://www.google.com/jsapi↵    at Error (native)↵    at HTMLScriptElement.c.onerror (file:///android_asset/www/js/javascript.plugins.min.js:15:429)"
    get stack: function () { [native code] }
    set stack: function () { [native code] }
    __proto__: d

But when I click on the link to the callback on the console (GET), it opens the link without a problem.

Any ideas? I'm using the latest geolocator (1.2.9).

Thank you,
Leandro

**Comment by MuTLY** [comment]
Ok, I figure it out.

Cordova is moving all it's plugins to npm (https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html)

So I had to remove all the older org.apache.cordova.* plugins and add the new ones, plus the new cordova-plugin-whitelist

All is good now.
