### ISSUE TITLE
Crashes when used with Electron

### ISSUE THREAD

**Issue by pronebird** [onury/geolocator#48]
```
Uncaught TypeError: Cannot read property '_' of undefined
    at /project/node_modules/geolocator/dist/geolocator.js:2989:19
    at Array.forEach (native)
    at Object.notateGlobalObj (/project/node_modules/geolocator/dist/geolocator.js:2988:17)
    at Function.jsonp (/project/node_modules/geolocator/dist/geolocator.js:3382:36)
    at Function.locateByIP (/project/node_modules/geolocator/dist/geolocator.js:986:37)
    at fallbackToIP (/project/node_modules/geolocator/dist/geolocator.js:704:40)
    at onPositionError (/project/node_modules/geolocator/dist/geolocator.js:716:18)
    at /project/node_modules/geolocator/dist/geolocator.js:2334:18
    at GeoWatcher.clear (/project/node_modules/geolocator/dist/geolocator.js:4933:30)
    at /project/node_modules/geolocator/dist/geolocator.js:2333:29
```

source:

```js
import geolocator from 'geolocator';

geolocator.config({
  language: "en",
  google: {
    version: "3",
    key: googleApiKey
  }
});

    const options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumWait: 10000,
      desiredAccuracy: 30,
      fallbackToIP: true, 
      addressLookup: true,
      timezone: true
    };

    geolocator.locate(options, (err, loc) => {
      console.log(err, loc);
    });
```

**Comment by onury** [comment]
Would you try adding this line right after your import:
`window.geolocator = geolocator;`

Pls see [this issue](https://github.com/onury/geolocator/issues/42#issuecomment-263767081) and [this SO post](http://stackoverflow.com/a/38556376/112731) I've answered.

**Comment by pronebird** [comment]
Ha yeah that worked!

**Comment by onury** [comment]
This is added in [v2.1.1](https://github.com/onury/geolocator/blob/master/CHANGELOG.md#v211-2017-03-11).
